Resource handler returned message: "Error occurred during operation 'CreateAssociation'." (RequestToken: 04de6fb4-3d16-76c6-4457-3fa8a612389a, HandlerErrorCode: GeneralServiceException)

# SSM Association to Apply the Domain Join Document
  SSMDomainJoinAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: !Ref myssmdocument
      Targets:
      - Key: InstanceIds
        Values:
          - !Ref EC2Instan
      Parameters:
        directoryId:
          - !Ref ADDirectoryId
        directoryName:
          - !Ref ADDirectoryName
        dnsIpAddresses:
          - !Ref ADDnsIpAddress1
          - !Ref ADDnsIpAddress2
      AssociationName: DomainJoinAssociation
      AutomationTargetParameterName: InstanceId
      MaxConcurrency: "1"
      MaxErrors: "0"
      ComplianceSeverity: CRITICAL
    DependsOn:
      - myssmdocument
      - EC2Instance
